[package]
name = "api_rsa"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-cors = "0.7.1"
actix-web = "4.11.0"
base64 = "0.22.1"
lazy_static = "1.5.0"
rsa = "0.9.8"
serde = { version = "1.0.228", features = ["derive"] }
